version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: automatizacion_backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/generated_docs:/app/generated_docs
      - ./backend/templates:/app/templates
      - ./backend/sql_app.db:/app/sql_app.db
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///sql_app.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: automatizacion_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
